name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: "PHPUnit with PHP ${{ matrix.php }}"

    strategy:
      matrix:
        php: [8.0, 8.1, 8.2, 8.3, 8.4, 8.5]

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer, cs2pr

      - uses: actions/checkout@v6

      - name: Cache Composer cache
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: composer-cache-php${{ matrix.php }}

      - name: Composer install
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPUnit
        run: php vendor/bin/phpunit

  static-analysis:
    name: "Static Analysis"

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring
          tools: composer, cs2pr

      - uses: actions/checkout@v6

      - name: Cache Composer cache
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: composer-cache-php${{ matrix.php }}

      - name: Composer install
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader

      - name: Covers validator
        run: php vendor/bin/covers-validator

      - name: PHPStan
        run: php vendor/bin/phpstan analyse --level=1 --error-format=checkstyle --no-progress src/ tests/ | cs2pr

      - name: PHPCS
        run: php vendor/bin/phpcs -q --report=checkstyle --no-colors | cs2pr

  coverge:
    name: "Code coverage"

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: mbstring
          tools: composer, cs2pr

      - uses: actions/checkout@v6

      - name: Cache Composer cache
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: composer-cache-php${{ matrix.php }}

      - name: Composer install
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPUnit
        run: php vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Download ocular.phar
        run: wget https://scrutinizer-ci.com/ocular.phar

      - name: Upload coverage.clover
        run: php ocular.phar code-coverage:upload --format=php-clover coverage.clover
